//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Flag { get; set; }
    }
}
